server:
  port: 8081

spring:
  application:
    name: oauth-server

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456